config/routes.rb
Rails.application.routes.draw do
  root to: "application#index"
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :paper_trail_versions, controller: 'versions'
  devise_scope :user do
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  resources :patients, :offices, :practitioners, :practitioner_professions,
            :users, :sessions, :therapies, :acts, :pathologies,
            :health_places, :health_place_types, :absences, :interactions,
            :interaction_objects, :interaction_types, :patients_acts, :schoolings,
            :schools, :school_types, :school_levels, :school_years, :addresses,
            :address_types, :contact_informations, :contact_information_types,
            :patients_pathologies, :patient_availabilities

  resources :waiting_lists do
    member do
      get :take_care
      get :add_interaction
      get :stop_registration
      get :patient_never_return
      get :care_confirm
      get :availability_not_compatible
      get :reregister_on_waiting_list
    end
  end

  get '/export_db', to: 'admin#export_db'
  get '/show_db', to: 'admin#show_db_view'
  get '/show_fixtures', to: 'admin#show_fixtures_view'

end

app/models/practitioner.rb
class Practitioner < ActiveRecord::Base
  has_paper_trail 
  resourcify
  belongs_to :practitioner_profession
  belongs_to :health_place
  has_many :sessions
  default_scope { order(:last_name, :first_name) }

  def to_label
    "#{self.last_name} #{self.first_name} (#{self.practitioner_profession.name})"
  end  

  def to_s
  	"#{self.first_name} #{self.last_name}"
  end	
end

app/controllers/practitioners_controller.rb
class PractitionersController < ApplicationController
  authorize_resource
  before_action :set_practitioner, only: [:show, :edit, :update, :destroy]
  # GET /practitioners
  def index
    @q = Practitioner.ransack(params[:q])
    @practitioners = @q.result
  end
  # GET /practitioners/1
  def show
    @events
  end

  # GET /practitioners/new
  def new
    @practitioner = Practitioner.new
  end

  # GET /practitioners/1/edit
  def edit
  end

  # POST /practitioners
  def create
    @practitioner = Practitioner.new(practitioner_params)

    if @practitioner.save
      redirect_to @practitioner, notice: 'Practitioner was successfully created.'
    else
      render :new
    end
  end
  # PATCH/PUT /practitioners/1
  def update
    if @practitioner.update(practitioner_params)
      redirect_to @practitioner, notice: 'Practitioner was successfully updated.'
    else
      render :edit
    end
  end
  # DELETE /practitioners/1
  def destroy
    @practitioner.destroy
    redirect_to practitioners_url, notice: 'Practitioner was successfully destroyed.'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practitioner
      @practitioner = Practitioner.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def practitioner_params

      params.require(:practitioner).permit(:first_name, :last_name, :birth_date, :birth_place, :practitioner_profession_id, :health_place_id)

    end
end

app/views/practitioners/_calendrier.html.erb
<%= week_calendar number_of_weeks: 1, events: sessions do |date, events| %>
  <div style="position: relative;">
    <% events.each do |event| %>
      <div class="event" style="position:absolute; top:<%= (((event.begin_date - event.begin_date.beginning_of_day)/(60*30))-(2*7)).to_i*40 %>px">
        <%= event.patient %>
        <%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, event %>
            <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_polymorphic_path(event) %>
            <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, event, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/practitioners/_form.html.erb
<%= simple_form_for(@practitioner) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <div class="form-group">
      <label for="first_name"><%= f.label :first_name %></label>
      <%= f.input :first_name, label: false, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <label for="last_name"><%= f.label :last_name %></label>
      <%= f.input :last_name, label: false, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <label for="birth_date"><%= f.label :birth_date %></label>
      <%= f.input :birth_date, label: false, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <label for="birth_place"><%= f.label :birth_place %></label>
      <%= f.input :birth_place, label: false, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <label for="practitioner_profession"><%= f.label :practitioner_profession %></label>
      <%= f.association :practitioner_profession, label: false, input_html: { class: "form-control" } %>
    </div>

    <div class="form-group">
      <label for="health_place"><%= f.label :health_place %></label>
      <%= f.association :health_place, label: false, input_html: { class: "form-control" } %>
    </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/practitioners/edit.html.erb
<h1>Editing Practitioner</h1>

<%= render 'form' %>

<%= link_to 'Show', @practitioner %> |
<%= link_to 'Back', practitioners_path %>

app/views/practitioners/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %><span class="badge"><%= @practitioners.count %></span></h1>

<div class="row">
  <div class="col-md-2">
    <legend class="filter-title"><%= t :filter_title %></legend>
  </div>
  <div class="col-md-3 btn-new-top">
    <% if can? :create, Practitioner %>
      <%= link_to ('<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> '+t('.new_button')).html_safe, url_for(action: :new), class: "btn btn-default" %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <fieldset class="filter-panel">
      <%= search_form_for @q do |f| %>

        <%= f.search_field :first_name_cont, {placeholder: t('activerecord.attributes.practitioner.first_name')} %>

        <%= f.search_field :last_name_cont, {placeholder: t('activerecord.attributes.practitioner.last_name')} %>

        <%= f.search_field :birth_date_cont, {placeholder: t('activerecord.attributes.practitioner.birth_date')} %>

        <%= f.search_field :birth_place_cont, {placeholder: t('activerecord.attributes.practitioner.birth_place')} %>

        <%= f.search_field :practitioner_profession_name_cont, {placeholder: t('activerecord.attributes.practitioner.practitioner_profession')} %>

        <%= f.search_field :health_place_name_cont, {placeholder: t('activerecord.attributes.practitioner.health_place')} %>

        <br>
        <br>
        <%= f.submit class: 'btn btn-default btn-search-filter' %>
      <% end %>
    </fieldset>
  </div>
  <div class="col-md-10">
    <table class="table table-hover table-condensed table-bordered">
      <thead>
        <tr>
    
          <th><%= sort_link(@q, :first_name, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :last_name, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :birth_date, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :birth_place, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :practitioner_profession_name, default_order: :asc) %></th>
    
          <th><%= sort_link(@q, :health_place_name, default_order: :asc) %></th>
    
          <th class="col-xs-1"></th>
        </tr>
      </thead>

      <tbody>
        <% @practitioners.each do |practitioner| %>
          <tr>
    
            <td><%= practitioner.first_name %></td>
    
            <td><%= practitioner.last_name %></td>
    
            <td><%= practitioner.birth_date %></td>
    
            <td><%= practitioner.birth_place %></td>
    
            <td><%= practitioner.practitioner_profession %></td>
    
            <td><%= practitioner.health_place %></td>
    
            <td>
              <%= link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, practitioner %>
              <% if can? :edit, practitioner %>
                <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_practitioner_path(practitioner) %>
              <% end %>
              <% if can? :destroy, practitioner %>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, practitioner, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/practitioners/new.html.erb
<h1>New Practitioner</h1>

<%= render 'form' %>

<%= link_to 'Back', practitioners_path %>

app/views/practitioners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professionnel de santé:</strong>
  <%= @practitioner.first_name %>
  <%= @practitioner.last_name %>
  <%= @practitioner.birth_date %>
  (<%= @practitioner.birth_place %>)
  <strong>Practitioner profession:</strong>
  <%= @practitioner.practitioner_profession %>
  <strong>Health place:</strong>
  <%= @practitioner.health_place %>
</p>

<%= link_to 'Edit', edit_practitioner_path(@practitioner) %> |
<%= link_to 'Back', practitioners_path %>

<%= render partial: 'calendrier', locals: {sessions: @practitioner.sessions} %>